#!/bin/bash
# Job Name and Files (also --job-name)
#SBATCH -J main
#Output and error (also --ouput, -error):
#SBATCH -o ./%x.%j.out
#SBATCH -e ./%x.%j.err
#Initial working directory (also --chdir):
#SBATCH -D ./
#Notification and type
#SBATCH --mail-type=END
#SBATCH --mail-user=iamnotalone1993@gmail.com
# Wall clock limit:
#SBATCH --time=00:20:00
#SBATCH --no-requeue
#Setup of execution environment
#SBATCH --export=NONE
#SBATCH --get-user-env
#SBATCH --account=pr58ci
#SBATCH --partition=general

#constraints are optional
#--constraint="scratch&work"

#Number of nodes and MPI tasks per node:
#SBATCH --nodes=128
#SBATCH --ntasks-per-node=48

#Important
module load slurm_setup

#Run the program
for i in `seq 5`; do mpiexec -n $SLURM_NTASKS ./main; done
#mpiexec -n $SLURM_NTASKS ./main
